import 'package:flutter/material.dart';

void main() => runApp(MonceiptsApp());

class MonceiptsApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(primarySwatch: Colors.blue),
      home: ReceiptViewer(txHash: "AA364E8T54"),
    );
  }
}

class ReceiptViewer extends StatelessWidget {
  final String txHash;
  ReceiptViewer({required this.txHash});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Monceipts")),
      body: Center(
        child: Column(
          children: [
            // Fetches the PNG generated by the Python Worker
            Image.network("http://localhost:8000/static/receipts/$txHash.png"),
            ElevatedButton(
              onPressed: () => print("Share Receipt"),
              child: Text("Share Proof of Purchase"),
            ),
          ],
        ),
      ),
    );
  }
}
